### ISSUE TITLE
serving nodejs app with custom domain fails with server not found

### ISSUE THREAD

**Issue by isawk** [GoogleCloudPlatform/google-cloud-node#1919]
We have an application built with angular2, served using nodejs/express. Application works as expected locally and on cloud engine through _project-id.appspot.com_ domain, however trying to reach application through custom domain fails with "Server not found" error.

custom domain *.dev.example.com has been configured for project-id, all other services are reachable and work, default services serving nodejs application fails with error "Server not found" 

#### Environment details

- Node.js version: v7.0.0
- npm version: 4.0.2
- google-cloud-node version: >=6.9.1

#### Steps to reproduce

1. Create google cloud project
2. Setup and deploy nodejs app
3. Configure customer domains with wildcard e.g. *.dev.example.com
4. Try reach default services serving nodejs application from dev.example.com

app.yaml

```yaml
runtime: nodejs
env: flex
skip_files:
- ^node_modules$
- ^app\.yaml
- ^README\..*
- \.gitignore
- ^\.git$
- ^grunt\.js
- ^src$
- ^e2e$
- \.editorconfig
- ^karma\.config\.js
- ^protractor\.conf\.js
- ^tslint\.json
```
